project:
  type: website

website:
  title: "My Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Micro-Ps
        menu:
          - text: Lab Reports
            href: MicroP/lab_reports/index.qmd
          - text: Final Project
            href: MicroP/final_proj/index.qmd
      - href: HPR
        text: HPR
      - href: resources.qmd
        text: Resources
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
