project:
  type: website

website:
  title: "Home Page"
  navbar:
    left:
      - href: resources.qmd
        text: Resources
      - href:   hobbies/index.qmd
        text: Hobbies
      - href: about.qmd
        text: About
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
