project:
  type: website

website:
  title: "Jason Bowman Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: MicroP
        text: Micro-Ps
      - href: HPR
        text: HPR
      - href: resources.qmd
        text: Resources
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true