project:
  type: website

website:
  title: "My Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Micro-Ps
        menu:
          - text: Lab Reports
            href: MicroP/lab_reports/index.qmd
          - text: Final Project
            href: https://jasonbowman55.github.io/squat_hero_website/
      - href: HPR
        text: HPR
      - href: hobbies/index.qmd
        text: Hobbies
        menu:
          - text: Annual Challenge
            href: hobbies/annual_challenge
      - href: resources.qmd
        text: Resources
      - href: about.qmd
        text: About
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
