---
title: THIS HOBBY HAS NOT BEEN FILLED OUT YET
draft: true
---

I began track and field during my 7th grade year. I have competed in track ever since, all the way through my college career, where I competed for Claremont McKenna track and field program, as a student at Harvey Mudd College.

# Why Sports
I began competing in sports at a very young age, starting with T-ball as soon as my parents could register me. Over the years, I played baseball for nine years (T-ball through 8th grade), American football for seven years (5th grade through 12th grade), and track & field for ten years (7th grade through my senior year of college). Through these experiences, I have not only gained a deep understanding of each sport but, more importantly, learned valuable lessons about myself, and how sports were able to facilitate those lessons.

Before making the following claim, I want to emphasize that I am not making a generalized or all-encompassing statement about sports and what they teach. While I believe these lessons and ways of thinking are common and apply to the majority of people involved in sports, I do not claim that they are a one-size-fits-all experience or guideline.

The freedom to make mistakes under pressure, accept failure, analyze its cause, find a solution, and refocus—all within a low-stakes environment—was one of the most valuable lessons I gained from sports, particularly in my early years playing baseball and football. The key to growth under pressure is experiencing that pressure in the first place. If my athletic experiences hadn't provided this, I would have missed a crucial opportunity to develop resilience.

It is this combination of being able to compete in a healthy way, work toward positive outcomes, and embrace challenges that make sports worth it from a young age. Baseball games, especially when I was just starting out, felt overwhelming and deeply significant in the moment. The pressure was real—people were watching, coaches were instructing, and every action reflected the effort I had put in. The same with football, my team was counting on me to do my job and complete each play, and coaches had put this trust into me. Learning to manage that stress and perform despite it shaped the way I handle challenges today, both on and off the field.

# Why Track?
Track and Field is my most recent and current athletic endeavor. I started in 7th grade and have continued through today, February 14, 2025 (Happy Valentine's Day!). Right now, I'm at the Podium in Spokane, Washington, about to throw the indoor weight for the last time in my college career. I am experiencing a sort of bitter sweetness that I have yet to hold in any of my other "last's" in sports. Yes I cried my last football game, but I was ultimately happy to be done playing, and have had little desire to play again. And baseball was fun, but as I will soon describe, I am so happy I got out when I did.

To answer "why track?" I feel that I first answer why not football? Because if this was not yet answered I feel there would be some emptiness and wondering left in me, curious if football could have been it. But after 7 years, I know football was not for me. It kept me active, I met life long friends, and made relationships with coaches and myself that are invalvuable, and I would not trade my time in football for anything else. However, even as a relatively decorated football player (in middle school and highschool terms of being decorated), I was never one to study the game, watch film, practice on my own, or even itch at the excitement of games or practice like my friends on the team. Or if I was itching at the chance to play, it was not for the game or even the opportunity to win, but the simple fact that I had the chance to hit someone, clean, hard, fair, and do it over and over again. Showing the results of my work in practice and the weight room, as well as itch my neanderthal primal brain through asserting my dominance over my fellow primates. While it may have felt like it at times, this was not anger, but an exercise in my competitive drive. I had not always enjoyed hitting and competing on the football field. But throughout time I began to enjoy the 1 on 1 competetiveness, along with the feeling of entering war with your brothers, another finger that worked to scratch my primal brain. But that was it, football was my medium to exercise, fratinise, assert myself, re-assert myself after being knocked down, and fight alongside a trusting group of fellow players. Football and the lessons I learned from it have and will never be about the game for me, and that is why I say no to football.

Next we must ask why not Baseball, and we must ask this for similar reasons as the previous. Yet this is a much simpler question to answer. 





Though once highschool baseball came around I knew something was different. Maybe it was that I truly enjoyed track more at the time, and that hind sight is 20/20. But I do remember feeling a different energy from the staff and players when I met them in an attempt to do baseball and track at the same time. A level of politics that should never exist in a below professional athletic setting began to show. Parents were involved, coaches had their favorites, teammates fought and argued for playing time. I look back now with confidence that I made the corect decision in dropping baseball for track and field at that time. While I will never know what my highschool baseball career would have looked like, I have friends who I know loved the game orders of magnitude more than I, who began to hate the game. 




00000000000
FORMAT
- intro dunction
    - what I have played, who am I, when Iplayd sports
- Why do sports matter (to me)
    - the importance of physical activity (for me)
    - why the pressure of sports (the fact that they feel like a big thing in the moment but are actually really safe and non-sconsesquential environments is a good thing, and if sports did not feel stressful or scary in the moment then the whole lession behind them would be useless and futile) (and how it effected me mainly)
    - A bit about each of baseball football and track and how they providedd me the saces to learnt these lessons about myself and why that was impotant to me (maybe basketball as well lol)
- WHY TRACK?
    - This will go less into the philosophical lessons that you learn fromt the sports (or of what I learned) and more into why I stopped playing them ie(football was not intereted in the actual game just hitting people and baseball was oo political)
    - why is track good for me and why it is important to me
        - how it supports my hobby of being in the weight room
        - how it supports the mindset of being indivisualistic in sports and everything
        - why it is fund, and the fact tat all the teams chear for eachother in some cases because people just want to see eachother do good no matter what (which is similar to the concept and philosophy of lifint in the weight room)
        - the people that I have met and the experiences that I have had
00000000000